config/routes.rb
ProjectCloset::Application.routes.draw do

  mount Attachinary::Engine => "/attachinary"

  resources :items

  devise_for :users

  resources :users

  root 'static_pages#front_page'

  get 'user_panel' => 'static_pages#user_panel'

  get 'command_center' => 'static_pages#command_center'

end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :user

	has_attachment :photo

	validates :user_id, presence: true
	validates :item_name, presence: true
	validates :quantity, presence: true


end

app/models/site_setting.rb
class SiteSetting < ActiveRecord::Base

	def self.title
		find(1).title
	end

	def self.subtitle
		find(1).subtitle
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :items, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for user
  	user_panel_path
  end

  def after_sign_out_path_for user
  	root_path
  end



  protected
  # Configure attributes that users may access in order to sign up or update their account.
  # These permitted parameters are required for Devise authentication when using with Rails 4 app.
  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) << :first_name << :last_name << :email
  	devise_parameter_sanitizer.for(:account_update) << :first_name << :last_name << :email
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = current_user.items.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to user_panel_path, notice: 'Item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @item }
      else
        format.html { render action: 'new' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to user_panel_path, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:item_name, :item_type, :item_color, :item_date_owned, :quantity, :size, :photo)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def front_page
	end

	def user_panel
		@items = current_user.items.all
	end

  def command_center
    if !current_user.admin
      redirect_to root_path
      flash[:notice] = "You are not authorized to go there."
    end
    @users = User.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] = "Successfully deleted User."
      redirect_to command_center_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/command_center/command_center.html.erb
<h1>Admin Command Center</h1>

app/views/items/_form.html.erb
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <%= simple_form_for(@item, html: { class: 'form-horizontal' }, wrapper: :horizontal_form) do |f| %>
      <% if @item.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

          <ul>
          <% @item.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <%= f.input :photo, as: :attachinary %>

      <%= f.input :item_name %>



      <%= f.input :item_type %>


      <%= f.input :item_color %>


      <%= f.input :item_date_owned %>


      <%= f.input :size %>


      <%= f.input :quantity, input_html: { placeholder: 1, value: 1 } %>

      <br/>
      <div class="actions text-center">
        <%= f.submit class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<div class="row text-center">
	<%= link_to 'Show', @item, class: 'btn btn-default' %> |
	<%= link_to 'Back', user_panel_path, class: 'btn btn-default' %>
</div>

app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Item name</th>
      <th>Item type</th>
      <th>Item color</th>
      <th>Item date owned</th>
      <th>Quantity</th>
      <th>Size</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.user_id %></td>
        <td><%= item.item_name %></td>
        <td><%= item.item_type %></td>
        <td><%= item.item_color %></td>
        <td><%= item.item_date_owned %></td>
        <td><%= item.quantity %></td>
        <td><%= item.size %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<div class="row text-center">
	<%= link_to 'Back', user_panel_path, class: 'btn btn-default' %>
</div>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<% if @item.photo? %>
  <%= cl_image_tag(@item.photo.path, { size: '125x125', crop: :fit }) %>
<% end %>
<p>
  <strong>Item name:</strong>
  <%= @item.item_name %>
</p>

<p>
  <strong>Item type:</strong>
  <%= @item.item_type %>
</p>

<p>
  <strong>Item color:</strong>
  <%= @item.item_color %>
</p>

<p>
  <strong>Item date owned:</strong>
  <%= @item.item_date_owned %>
</p>

<p>
  <strong>Date uploaded:</strong>
  <%= @item.created_at.strftime("%b %d %Y") %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @item.quantity %>
</p>

<p>
  <strong>Size:</strong>
  <%= @item.size %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', user_panel_path %> |
<%= link_to 'Destroy', item_path, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to( SiteSetting.title, root_path, class: 'navbar-brand') %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if !user_signed_in? %>
        <li><%= link_to 'Sign in / Register', new_user_session_path %></li>
        <% else %>
        <li><%= link_to 'My closet', user_panel_path %></li>
        <% end %> <%# end !user_signed_in? %>
        <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'My account', edit_user_registration_path %></li>
            <% if current_user.admin %>
              <li><%= link_to 'Command Center', command_center_path %><li>
            <% end %>
            <li class="divider"></li>
            <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
        <% end %> <%# end user_signed_in? %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_header.html.erb.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to( SiteSetting.title, root_path, class: 'navbar-brand') %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if !user_signed_in? %>
        <li><%= link_to 'Sign in / Register', new_user_session_path %></li>
        <% end %> <%# end !user_signed_in? %>
        <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
        <% end %> <%# end user_signed_in? %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>ProjectCloset</title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= cloudinary_js_config %>
	  <%= csrf_meta_tags %>
	  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	  <meta http-equiv="X-UA-Compatible" content="IE=10; IE=9; IE=8; IE=7; IE=EDGE" />
	</head>
	<body>
		<%= render 'layouts/header.html.erb' %>
		<div class="container-fluid">
			<% flash.each do |name, msg| %>
				<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
			<% end %>
			<%= yield %>
		</div>
	</body>
</html>

app/views/static_pages/command_center.html.erb
<h1>Admin Command Center</h1>
<table class="table table-striped">
  <th>
    <td>First Name</td>
    <td>Last Name</td>
    <td>Email</td>
    <td>Delete</td>
  </th>
  <% @users.each do |user| %>
    <tr>
      <td></td>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.email %></td>
      <td><%= link_to "Delete User", user_path(user.id), :confirm => "Are you sure?", :method => :delete %></td>
    </tr>
  <% end %>
</table>

app/views/static_pages/front_page.html.erb
<h1><%= SiteSetting.subtitle %></h1>

app/views/static_pages/user_panel.html.erb
<h1>My Closet</h1>
<div class='row text-center'>
  <%= link_to "New Item", new_item_path, class: 'btn btn-primary' %>
</div>
<br/>

<div class="gridster">
  <ul>
  <% @items.each do |item| %>
    <li class="gridster-cell" data-row="1" data-col="1" data-sizex="2" data-sizey="2">
      <% if item.photo? %>
        <div class='text-center gridster-image'><%= cl_image_tag(item.photo.path, { size: '125x125', crop: :fit }) %></div>
      <% end %>
      <%= link_to(item) do %>
        <h4 class='text-center'><%= item.item_name %></h4>
      <% end %>
      <p class='text-center'><%= item.item_type %></p>
      <p class='text-center'><%= item.item_color %></p>
    </li>
  <% end %>
  </ul>
</div>
<br/>


<%
=begin %>
<div id="masonry-container" class="gridster transitions-enabled centered infinite-scroll clearfix">
  <% @items.reverse.each do |item| %>
    <%= link_to(item) do %>
      <div class="box col2">
        <% if item.photo? %>
          <div class='text-center gridster-image'><%= cl_image_tag(item.photo.path, { size: '125x125', crop: :fit }) %></div>
        <% end %>
        <h4 class='text-center'><%= item.item_name %></h4>
        <p class='text-center'><%= item.item_type %></p>
        <p class='text-center'><%= item.item_color %></p>
      </div>
    <% end %>
  <% end %>
</div>
<%
=end %>